parameters:
  services: []

jobs:
  - job: Build_service
    displayName: Build services
    dependsOn: Prepare_environment
    variables:
      dockerImageTag: $[dependencies.Prepare_environment.outputs['setGlobalVarStep.dockerImageTag']]
    pool:
      name: default
    steps:
      - ${{ each service in parameters.services }}:
        - task: DockerCompose@0
          displayName: Compose build ${{ service }}
          inputs:
            dockerComposeCommand: 'build ${{ service }}'
            containerregistrytype: Container Registry
            dockerComposeFile: docker-compose.yml
            qualifyImageNames: true
            projectName: ''
            dockerComposeFileArgs: |
              TAG=$(dockerImageTag)
