parameters:
  services: ''
  registryEndpoint: ''

jobs:
  - job: Publish_Docker_Images
    displayName: Publish images
    variables:
      dockerImageTag: $[dependencies.Prepare_environment.outputs['setGlobalVarStep.dockerImageTag']]
    dependsOn:
    - Prepare_environment
    pool:
      name: default
    steps:
      - ${{ each service in parameters.services }}:
        - task: DockerCompose@0
          displayName: Compose push ${{ service }}
          inputs:
            dockerComposeCommand: 'push ${{ service }}'
            containerregistrytype: Container Registry
            dockerRegistryEndpoint: ${{ parameters.registryEndpoint }}
            dockerComposeFile: docker-compose.yml
            qualifyImageNames: true
            projectName: ""
            includeLatestTag: true
            dockerComposeFileArgs: |
              TAG=$(dockerImageTag)
